/*

    GenreParent
    =====
    Stores the information for the "Genres"- types of music this thing can output, as ranges.
    
    this.modes = [modes], a list of modes, weighted by number of duplicates; i.e. [1, 2, 3] is all 33% chance, but [1, 1, 1, 2, 3] is 60%, 20%, 20%
    this.bpms = [min int, max int] bpms 
    this.moodChipRanges = {field: [min int, max int]}- moodChipRanges- RN an object with the 5 moodChip values and min/max ranges
    this.instrumentList = Obj/instrumentList- Should be a list of acceptable instruments, but RN it's just the list object

    function generateRandomInstance()- generates a GenreInstance based on it's own values

    GenreInstance
    =====
    Stores the information for an instance of a "Genre"- choose from the parent's ranges.

    this.mode = The mode that's chosen- int[1-7]
    this.bpm = the bpm value that's chosen- int[~40-~200]
    this.moodChip = Obj/MoodChip generated by number
    this.instrumentList = Obj/InstrumentList- RN just passed down, but should be randomized too.


*/

import MoodChip from './moodChip.js'

export default class GenreParent {
    constructor({ name, category, modes, bpms, moodChipRanges, instrumentList }) {
        this.name = name
        this.category = category

        this.modes = modes
        this.bpms = bpms
        this.moodChipRanges = moodChipRanges
        this.instrumentList = instrumentList
    }

    generateRandomInstance() {
        let mode = randomValueFromArray(this.modes)
        let bpm = randomValueFromRange(this.bpms)

        let moodChip = {}
        
        moodChip.resonance = randomValueFromRange(this.moodChipRanges.resonance)
        moodChip.tension = randomValueFromRange(this.moodChipRanges.tension)
        moodChip.repetition = randomValueFromRange(this.moodChipRanges.repetition)
        moodChip.spread = randomValueFromRange(this.moodChipRanges.spread)
        moodChip.excitement = randomValueFromRange(this.moodChipRanges.excitement)

        moodChip = new MoodChip(moodChip)

        this.instrumentList.chooseInstrumentList()
        let instrumentList = this.instrumentList
        
        return new GenreInstance({mode, bpm, moodChip, instrumentList })
    }

}

class GenreInstance {
    constructor({ mode, bpm, moodChip, instrumentList }) {
        this.mode = mode
        this.bpm = bpm
        this.moodChip = moodChip
        this.instrumentList = instrumentList
    }
}

function randomValueFromRange(range) {
    return Math.floor((Math.random() * (range[1] - range[0]) + 1) + range[0])
}

function randomValueFromArray(array) {
    let choiceAmount = array.length
    return array[Math.floor((Math.random() * (choiceAmount - 1))) + 1]
}


